# Generated by Django 4.0.1 on 2022-01-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_finish_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_finish',
        ),
    ]
