# Generated by Django 4.0.1 on 2022-01-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='mina samaan', max_length=150),
        ),
    ]
